In [6]:
import pandas as pd 
import numpy as np

In [7]:
veriler=np.random.randint(1,50,size=[4,5]) #numpy sınıfından 1'den 50'ye kadar 4 satır 5 sütünluk rastgele sayılardan olusan bir dizi

In [8]:
veriler

array([[13, 35, 41, 22, 15],
       [39,  9, 23, 49, 17],
       [ 5, 27, 24, 45, 34],
       [ 6, 44, 35, 13, 22]])

In [10]:
df=pd.DataFrame(veriler) #veriler dizsinden olusan df adında bir dataframe olusturduk.

In [11]:
df

    0   1   2   3   4
0  13  35  41  22  15
1  39   9  23  49  17
2   5  27  24  45  34
3   6  44  35  13  22

In [18]:
df=pd.DataFrame(veriler,columns=["s1","s2","s3","s4","s5"],index=["st1","st2","st3","st4"]) #columns ile sütün isimleri,index ile satır isimleri degistirilir
df

     s1  s2  s3  s4  s5
st1  13  35  41  22  15
st2  39   9  23  49  17
st3   5  27  24  45  34
st4   6  44  35  13  22

In [ ]:
veriler=[["melek","Erisigin",16],["Melek","erisgin",16]]

In [21]:
df=pd.DataFrame(veriler,columns=["isim","soyisim","yas"],index=["ögr1","ögr2"])
df

ValueError: Shape of passed values is (4, 5), indices imply (2, 3)

In [24]:
df=pd.read_csv("diabetes_data_upload.csv")
df

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,39,Female,Yes,Yes,Yes,No,Yes,No,No,Yes,No,Yes,Yes,No,No,No,Positive
516,48,Female,Yes,Yes,Yes,Yes,Yes,No,No,Yes,Yes,Yes,Yes,No,No,No,Positive
517,58,Female,Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,No,Yes,Yes,No,Yes,Positive
518,32,Female,No,No,No,Yes,No,No,Yes,Yes,No,Yes,No,No,Yes,No,Negative
519,42,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative

In [27]:
df.tail(3)#sondan 3 satır gosterir

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
517,58,Female,Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,No,Yes,Yes,No,Yes,Positive
518,32,Female,No,No,No,Yes,No,No,Yes,Yes,No,Yes,No,No,Yes,No,Negative
519,42,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative

In [28]:
df.shape# satır ve sütün sayısını verir

(520, 17)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 520 non-null    int64
 1   Gender              520 non-null    object
 2   Polyuria            520 non-null    object
 3   Polydipsia          520 non-null    object
 4   sudden weight loss  520 non-null    object
 5   weakness            520 non-null    object
 6   Polyphagia          520 non-null    object
 7   Genital thrush      520 non-null    object
 8   visual blurring     520 non-null    object
 9   Itching             520 non-null    object
 10  Irritability        520 non-null    object
 11  delayed healing     520 non-null    object
 12  partial paresis     520 non-null    object
 13  muscle stiffness    520 non-null    object
 14  Alopecia            520 non-null    object
 15  Obesity             520 non-null    object
 16  class               520 non-null    object
dtypes: int64(1), object(16)
memory usage: 69.2+ KB

In [31]:
df.ndim # veri setinin boyutunu gösterir

2